### ISSUE TITLE
Consider adding the RMI-PACTA `pkgdown` by default

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.r.package#12]
@cjyetman thoughts? Do we want a new package to automatically generate a pkgdown website? I don't see why not.

**Comment by AlexAxthelm** [comment]
I've not used pkgdown extensively. does that imply the existence of a long-lived `gh-pages` branch?

**Comment by cjyetman** [comment]
> I've not used pkgdown extensively. does that imply the existence of a long-lived `gh-pages` branch?

yes
