### ISSUE TITLE
☠️ consider archiving this repo

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.r.package#22]
@RMI-PACTA/developers 
Do any of you (or have any of you) ever actually used this repo to start an R package? 

My assumption is no, and if not I would propose we just delete this template package.

**Comment by AlexAxthelm** [comment]
works from my side.

**Comment by cjyetman** [comment]
don't believe I ever used it, though I did apparently make some commits here 🤷🏻

**Comment by Antoine-Lalechere** [comment]
I think I used it to create some package

**Comment by MonikaFu** [comment]
I haven't used it I believe.

**Comment by jacobvjk** [comment]
I don't recall if I have used it, but I don't feel the need to keep it

**Comment by jdhoffa** [comment]
Ok, I think I will elect to archive it. 
@Antoine-Lalechere if you need support making a package in the future, reach out to us! and we can demo `usethis` :-)
